// Editor for server permission roles (serverconfig.json "Roles" + "DefaultRoleCode").

const ALL_PRIVILEGES = [
  "chat", "build", "useblock", "buildblockseverywhere", "useblockseverywhere",
  "attackplayers", "attackcreatures", "freemove", "gamemode", "pickingrange",
  "areamodify", "selfkill", "controlplayergroups", "manageplayergroups",
  "manageotherplayergroups", "commandplayer", "kick", "ban", "whitelist",
  "announce", "readlists", "setwelcome", "give", "setspawn", "tp", "time",
  "grantrevoke", "controlserver", "worldedit", "root",
];

// EnumGameMode in Vintage Story.
const GAME_MODES = [
  { value: 0, label: "Guest" },
  { value: 1, label: "Survival" },
  { value: 2, label: "Creative" },
  { value: 3, label: "Spectator" },
];

const ROLE_COLORS = [
  "White", "Gray", "DarkGray", "Green", "LightGreen", "Cyan", "LightBlue",
  "Blue", "Red", "Yellow", "Orange", "Magenta",
];

const DEFAULT_ROLE_CODE = "suplayer";

// Stock roles as generated by the server on first start.
const DEFAULT_ROLES = [
  { Code: "suvisitor", PrivilegeLevel: -1, Name: "Survival Visitor", Description: "Can only visit this world and chat but not use/place/break anything", DefaultSpawn: null, ForcedSpawn: null, Privileges: ["chat"], RuntimePrivileges: [], DefaultGameMode: 1, Color: "Green", LandClaimAllowance: 0, LandClaimMinSize: { X: 5, Y: 5, Z: 5 }, LandClaimMaxAreas: 3, AutoGrant: false },
  { Code: "crvisitor", PrivilegeLevel: -1, Name: "Creative Visitor", Description: "Can only visit this world, chat and fly but not use/place/break anything", DefaultSpawn: null, ForcedSpawn: null, Privileges: ["chat"], RuntimePrivileges: [], DefaultGameMode: 2, Color: "DarkGray", LandClaimAllowance: 0, LandClaimMinSize: { X: 5, Y: 5, Z: 5 }, LandClaimMaxAreas: 3, AutoGrant: false },
  { Code: "limitedsuplayer", PrivilegeLevel: -1, Name: "Limited Survival Player", Description: "Can use/place/break blocks only in permitted areas (priv level -1), create/manage player groups and chat", DefaultSpawn: null, ForcedSpawn: null, Privileges: ["controlplayergroups", "manageplayergroups", "chat", "build", "useblock", "attackcreatures", "attackplayers", "selfkill"], RuntimePrivileges: [], DefaultGameMode: 1, Color: "White", LandClaimAllowance: 0, LandClaimMinSize: { X: 5, Y: 5, Z: 5 }, LandClaimMaxAreas: 3, AutoGrant: false },
  { Code: "limitedcrplayer", PrivilegeLevel: -1, Name: "Limited Creative Player", Description: "Can use/place/break blocks in only in permitted areas (priv level -1), create/manage player groups, chat, fly and set his own game mode (= allows fly and change of move speed)", DefaultSpawn: null, ForcedSpawn: null, Privileges: ["controlplayergroups", "manageplayergroups", "chat", "build", "useblock", "gamemode", "freemove", "attackcreatures", "attackplayers", "selfkill"], RuntimePrivileges: [], DefaultGameMode: 2, Color: "LightGreen", LandClaimAllowance: 0, LandClaimMinSize: { X: 5, Y: 5, Z: 5 }, LandClaimMaxAreas: 3, AutoGrant: false },
  { Code: "suplayer", PrivilegeLevel: 0, Name: "Survival Player", Description: "Can use/place/break blocks in unprotected areas (priv level 0), create/manage player groups and chat. Can claim an area of up to 8 chunks.", DefaultSpawn: null, ForcedSpawn: null, Privileges: ["controlplayergroups", "manageplayergroups", "chat", "areamodify", "build", "useblock", "attackcreatures", "attackplayers", "selfkill"], RuntimePrivileges: [], DefaultGameMode: 1, Color: "White", LandClaimAllowance: 262144, LandClaimMinSize: { X: 5, Y: 5, Z: 5 }, LandClaimMaxAreas: 3, AutoGrant: false },
  { Code: "crplayer", PrivilegeLevel: 100, Name: "Creative Player", Description: "Can use/place/break blocks in all areas (priv level 100), create/manage player groups, chat, fly and set his own game mode. Can claim an area of up to 40 chunks.", DefaultSpawn: null, ForcedSpawn: null, Privileges: ["controlplayergroups", "manageplayergroups", "chat", "areamodify", "build", "useblock", "gamemode", "freemove", "attackcreatures", "attackplayers", "selfkill"], RuntimePrivileges: [], DefaultGameMode: 2, Color: "LightGreen", LandClaimAllowance: 1310720, LandClaimMinSize: { X: 5, Y: 5, Z: 5 }, LandClaimMaxAreas: 6, AutoGrant: false },
  { Code: "sumod", PrivilegeLevel: 200, Name: "Survival Moderator", Description: "Can use/place/break blocks everywhere (priv level 200), manage player groups, chat, kick/ban players and do serverwide announcements.", DefaultSpawn: null, ForcedSpawn: null, Privileges: ["controlplayergroups", "manageplayergroups", "manageotherplayergroups", "chat", "areamodify", "build", "useblock", "buildblockseverywhere", "useblockseverywhere", "kick", "ban", "announce", "readlists", "attackcreatures", "attackplayers", "selfkill"], RuntimePrivileges: [], DefaultGameMode: 1, Color: "Cyan", LandClaimAllowance: 1310720, LandClaimMinSize: { X: 5, Y: 5, Z: 5 }, LandClaimMaxAreas: 60, AutoGrant: false },
  { Code: "crmod", PrivilegeLevel: 500, Name: "Creative Moderator", Description: "Can use/place/break blocks everywhere (priv level 500), manage player groups, chat, kick/ban players, fly and set game modes.", DefaultSpawn: null, ForcedSpawn: null, Privileges: ["controlplayergroups", "manageplayergroups", "manageotherplayergroups", "chat", "areamodify", "build", "useblock", "buildblockseverywhere", "useblockseverywhere", "kick", "ban", "gamemode", "freemove", "commandplayer", "announce", "readlists", "attackcreatures", "attackplayers", "selfkill"], RuntimePrivileges: [], DefaultGameMode: 2, Color: "Cyan", LandClaimAllowance: 1310720, LandClaimMinSize: { X: 5, Y: 5, Z: 5 }, LandClaimMaxAreas: 60, AutoGrant: false },
  { Code: "admin", PrivilegeLevel: 99999, Name: "Admin", Description: "Has all privileges, including giving other players admin status.", DefaultSpawn: null, ForcedSpawn: null, Privileges: ["build", "useblock", "buildblockseverywhere", "useblockseverywhere", "attackplayers", "attackcreatures", "freemove", "gamemode", "pickingrange", "chat", "kick", "ban", "whitelist", "setwelcome", "announce", "readlists", "give", "areamodify", "setspawn", "controlserver", "tp", "time", "grantrevoke", "root", "commandplayer", "controlplayergroups", "manageplayergroups", "selfkill", "manageotherplayergroups", "worldedit"], RuntimePrivileges: [], DefaultGameMode: 1, Color: "LightBlue", LandClaimAllowance: 2147483647, LandClaimMinSize: { X: 5, Y: 5, Z: 5 }, LandClaimMaxAreas: 99999, AutoGrant: true },
];

const Roles = (() => {
  const clone = (x) => JSON.parse(JSON.stringify(x));
  let roles = clone(DEFAULT_ROLES);
  let defaultRoleCode = DEFAULT_ROLE_CODE;
  let onChangeCb = () => {};
  let bodyEl = null;
  let defaultSelect = null;

  function el(tag, attrs = {}, children = []) {
    const node = document.createElement(tag);
    for (const [k, v] of Object.entries(attrs)) {
      if (k === "class") node.className = v;
      else if (k === "text") node.textContent = v;
      else if (v !== null && v !== undefined) node.setAttribute(k, v);
    }
    for (const c of [].concat(children)) {
      if (c) node.appendChild(typeof c === "string" ? document.createTextNode(c) : c);
    }
    return node;
  }

  function labeled(labelText, control) {
    return el("label", { class: "role-field" }, [el("span", { text: labelText }), control]);
  }

  function numInput(value, onInput, attrs = {}) {
    const i = el("input", Object.assign({ type: "number", class: "f-number role-num" }, attrs));
    i.value = value;
    i.addEventListener("input", () => onInput(i.value));
    return i;
  }

  function refreshDefaultSelect() {
    if (!defaultSelect) return;
    defaultSelect.textContent = "";
    for (const r of roles) {
      defaultSelect.appendChild(el("option", { value: r.Code, text: r.Code }));
    }
    defaultSelect.value = roles.some((r) => r.Code === defaultRoleCode)
      ? defaultRoleCode : (roles[0] && roles[0].Code) || "";
    defaultRoleCode = defaultSelect.value;
  }

  function buildRoleCard(role, index) {
    const card = el("details", { class: "role-card" });
    const title = el("span", { class: "role-card-title" });
    const codeBadge = el("code", { class: "role-code", text: role.Code });
    title.appendChild(codeBadge);
    title.appendChild(el("span", { class: "role-card-name", text: role.Name || "" }));
    const removeBtn = el("button", { type: "button", class: "btn btn-ghost role-remove", text: "Remove" });
    removeBtn.addEventListener("click", (e) => {
      e.preventDefault();
      roles.splice(index, 1);
      render();
      onChangeCb();
    });
    const summary = el("summary", { class: "role-card-summary" }, [title, removeBtn]);
    card.appendChild(summary);

    const grid = el("div", { class: "role-grid" });

    const codeInput = el("input", { type: "text", class: "f-text" });
    codeInput.value = role.Code;
    codeInput.addEventListener("input", () => { role.Code = codeInput.value; codeBadge.textContent = role.Code; onChangeCb(); });
    codeInput.addEventListener("change", refreshDefaultSelect);
    grid.appendChild(labeled("Code", codeInput));

    const nameInput = el("input", { type: "text", class: "f-text" });
    nameInput.value = role.Name || "";
    nameInput.addEventListener("input", () => { role.Name = nameInput.value; onChangeCb(); });
    grid.appendChild(labeled("Name", nameInput));

    grid.appendChild(labeled("Privilege level", numInput(role.PrivilegeLevel, (v) => { role.PrivilegeLevel = parseInt(v, 10) || 0; onChangeCb(); }, { step: 1 })));

    const gmSelect = el("select", { class: "f-select" });
    for (const gm of GAME_MODES) gmSelect.appendChild(el("option", { value: gm.value, text: gm.label }));
    gmSelect.value = role.DefaultGameMode;
    gmSelect.addEventListener("change", () => { role.DefaultGameMode = parseInt(gmSelect.value, 10); onChangeCb(); });
    grid.appendChild(labeled("Default game mode", gmSelect));

    const colorInput = el("input", { type: "text", class: "f-text", list: "role-colors" });
    colorInput.value = role.Color || "";
    colorInput.addEventListener("input", () => { role.Color = colorInput.value; onChangeCb(); });
    grid.appendChild(labeled("Color", colorInput));

    grid.appendChild(labeled("Land claim allowance", numInput(role.LandClaimAllowance, (v) => { role.LandClaimAllowance = parseInt(v, 10) || 0; onChangeCb(); }, { step: 1, min: 0 })));
    grid.appendChild(labeled("Land claim max areas", numInput(role.LandClaimMaxAreas, (v) => { role.LandClaimMaxAreas = parseInt(v, 10) || 0; onChangeCb(); }, { step: 1, min: 0 })));

    // Land claim min size X/Y/Z
    const mkMin = (axis) => numInput(role.LandClaimMinSize[axis], (v) => { role.LandClaimMinSize[axis] = parseInt(v, 10) || 0; onChangeCb(); }, { step: 1, min: 1 });
    const minWrap = el("div", { class: "role-minsize" }, [mkMin("X"), mkMin("Y"), mkMin("Z")]);
    grid.appendChild(labeled("Min claim size (X/Y/Z)", minWrap));

    const autoGrant = el("input", { type: "checkbox", class: "f-toggle" });
    autoGrant.checked = !!role.AutoGrant;
    autoGrant.addEventListener("change", () => { role.AutoGrant = autoGrant.checked; onChangeCb(); });
    grid.appendChild(labeled("Auto grant", autoGrant));

    const descInput = el("input", { type: "text", class: "f-text" });
    descInput.value = role.Description || "";
    descInput.addEventListener("input", () => { role.Description = descInput.value; onChangeCb(); });
    const descField = labeled("Description", descInput);
    descField.classList.add("role-field-wide");
    grid.appendChild(descField);

    card.appendChild(grid);

    // Privileges checklist
    card.appendChild(el("p", { class: "role-priv-title", text: "Privileges" }));
    const privGrid = el("div", { class: "role-privs" });
    for (const priv of ALL_PRIVILEGES) {
      const cb = el("input", { type: "checkbox" });
      cb.checked = role.Privileges.includes(priv);
      cb.addEventListener("change", () => {
        if (cb.checked) { if (!role.Privileges.includes(priv)) role.Privileges.push(priv); }
        else { role.Privileges = role.Privileges.filter((p) => p !== priv); }
        onChangeCb();
      });
      privGrid.appendChild(el("label", { class: "role-priv" }, [cb, el("span", { text: priv })]));
    }
    card.appendChild(privGrid);

    return card;
  }

  function render() {
    if (!bodyEl) return;
    bodyEl.textContent = "";

    const bar = el("div", { class: "role-bar" });
    const addBtn = el("button", { type: "button", class: "btn", text: "+ Add role" });
    addBtn.addEventListener("click", () => {
      roles.push({ Code: "newrole", PrivilegeLevel: 0, Name: "New Role", Description: "", DefaultSpawn: null, ForcedSpawn: null, Privileges: ["chat"], RuntimePrivileges: [], DefaultGameMode: 1, Color: "White", LandClaimAllowance: 0, LandClaimMinSize: { X: 5, Y: 5, Z: 5 }, LandClaimMaxAreas: 3, AutoGrant: false });
      render();
      onChangeCb();
    });
    const resetBtn = el("button", { type: "button", class: "btn btn-ghost", text: "Reset roles" });
    resetBtn.addEventListener("click", () => { roles = clone(DEFAULT_ROLES); defaultRoleCode = DEFAULT_ROLE_CODE; render(); onChangeCb(); });

    defaultSelect = el("select", { class: "f-select" });
    defaultSelect.addEventListener("change", () => { defaultRoleCode = defaultSelect.value; onChangeCb(); });

    bar.appendChild(addBtn);
    bar.appendChild(resetBtn);
    bar.appendChild(el("label", { class: "role-default" }, [el("span", { text: "Default role:" }), defaultSelect]));
    bodyEl.appendChild(bar);

    const list = el("div", { class: "role-list" });
    roles.forEach((role, i) => list.appendChild(buildRoleCard(role, i)));
    bodyEl.appendChild(list);

    refreshDefaultSelect();
  }

  function build(container, onChange) {
    onChangeCb = onChange || (() => {});
    const details = el("details", { class: "cat", id: "section-roles" });
    const summary = el("summary", { class: "cat-summary" }, [
      el("span", { class: "cat-name", text: "Server roles" }),
      el("span", { class: "cat-count", text: String(roles.length) }),
    ]);
    bodyEl = el("div", { class: "cat-body" });
    details.appendChild(summary);
    details.appendChild(bodyEl);
    container.appendChild(details);

    // shared <datalist> for colors
    const dl = el("datalist", { id: "role-colors" });
    for (const c of ROLE_COLORS) dl.appendChild(el("option", { value: c }));
    container.appendChild(dl);

    render();
  }

  // Returns { roles, defaultRoleCode, changed } — changed=false means stock roles.
  function getConfig() {
    const changed = JSON.stringify(roles) !== JSON.stringify(DEFAULT_ROLES)
      || defaultRoleCode !== DEFAULT_ROLE_CODE;
    return { roles: clone(roles), defaultRoleCode, changed };
  }

  function setConfig(cfg) {
    if (cfg && Array.isArray(cfg.roles)) roles = clone(cfg.roles);
    if (cfg && cfg.defaultRoleCode) defaultRoleCode = cfg.defaultRoleCode;
    render();
  }

  return { build, getConfig, setConfig, DEFAULT_ROLES, DEFAULT_ROLE_CODE };
})();
