// World config settings (values/defaults from https://wiki.vintagestory.at/World_Configuration).
// Field: { key, label, type: bool|int|float|enum|string, default, min/max/step, options, help, creationOnly }.
// Category and field order drives the UI order.

const SCHEMA = [
  {
    id: "general",
    title: "General",
    fields: [
      { key: "gameMode", label: "Game mode", type: "enum", default: "survival",
        options: [
          { value: "survival", label: "Survival" },
          { value: "creative", label: "Creative" },
        ], help: "Default game mode of the world." },
      { key: "deathPunishment", label: "Death punishment", type: "enum", default: "drop",
        options: [
          { value: "drop", label: "Drop items" },
          { value: "keep", label: "Keep items" },
        ], help: "What happens to the inventory on death." },
      { key: "droppedItemsTimer", label: "Dropped items timer (s)", type: "int", default: 600,
        min: 0, max: 100000, step: 10, help: "Seconds until dropped items despawn." },
      { key: "spawnRadius", label: "Spawn radius (blocks)", type: "int", default: 50,
        min: 0, max: 100000, step: 10, help: "Radius around world spawn in which players appear." },
      { key: "startingClimate", label: "Starting climate", type: "enum", default: "temperate",
        options: [
          { value: "hot", label: "Hot" },
          { value: "warm", label: "Warm" },
          { value: "temperate", label: "Temperate" },
          { value: "cool", label: "Cool" },
          { value: "icy", label: "Icy" },
        ], help: "Climate around the starting area." },
      { key: "temporalGearRespawnUses", label: "Temporal gear respawn uses", type: "int",
        default: 20, min: -1, max: 9999, step: 1,
        help: "How often a temporal gear can be used to set the respawn point (-1 = unlimited)." },
      { key: "graceTimer", label: "Grace timer (days)", type: "int", default: 0, min: 0, max: 1000, step: 1,
        help: "Days without hostile creatures at the start." },
    ],
  },

  {
    id: "survival",
    title: "Survival challenges",
    fields: [
      { key: "seasons", label: "Seasons", type: "enum", default: "enabled",
        options: [
          { value: "enabled", label: "Enabled (cycle)" },
          { value: "spring", label: "Always spring" },
          { value: "summer", label: "Always summer" },
          { value: "fall", label: "Always fall" },
          { value: "winter", label: "Always winter" },
        ], help: "Seasonal cycle or a fixed season." },
      { key: "playerlives", label: "Player lives", type: "int", default: -1, min: -1, max: 1000, step: 1,
        help: "Number of lives per player (-1 = infinite)." },
      { key: "lungCapacity", label: "Lung capacity (ms)", type: "int", default: 40000,
        min: 1000, max: 200000, step: 1000, help: "Time underwater before taking damage." },
      { key: "daysPerMonth", label: "Days per month", type: "int", default: 9, min: 1, max: 1000, step: 1,
        help: "Length of a month (affects season length)." },
      { key: "harshWinters", label: "Harsh winters", type: "bool", default: true,
        help: "Winters with cold damage and frozen ground." },
      { key: "blockGravity", label: "Block gravity", type: "enum", default: "sandgravel",
        options: [
          { value: "sandgravel", label: "Sand & gravel" },
          { value: "sandgravelsoil", label: "Sand, gravel & soil" },
        ], help: "Which blocks are affected by gravity." },
      { key: "caveIns", label: "Cave-ins", type: "enum", default: "off",
        options: [
          { value: "off", label: "Off" },
          { value: "on", label: "On" },
        ], help: "Unstable rock can collapse." },
      { key: "allowFallingBlocks", label: "Falling blocks", type: "bool", default: true,
        help: "Blocks fall due to gravity." },
      { key: "allowFireSpread", label: "Fire spread", type: "bool", default: true,
        help: "Fire spreads to neighbouring blocks." },
      { key: "allowUndergroundFarming", label: "Underground farming", type: "bool", default: false,
        help: "Crops grow without sky light." },
      { key: "bodyTemperatureResistance", label: "Body temperature resistance", type: "float", default: 0,
        min: -40, max: 40, step: 1, help: "Shifts the tolerated temperature (degrees)." },
      { key: "creatureHostility", label: "Creature hostility", type: "enum", default: "aggressive",
        options: [
          { value: "aggressive", label: "Aggressive" },
          { value: "passive", label: "Passive" },
          { value: "off", label: "Off" },
        ], help: "Behaviour of hostile creatures." },
      { key: "creatureStrength", label: "Creature strength", type: "float", default: 1, min: 0, max: 99, step: 0.1,
        help: "Damage multiplier of hostile creatures." },
      { key: "creatureSwimSpeed", label: "Creature swim speed", type: "float", default: 2, min: 0.5, max: 3, step: 0.1,
        help: "Swim speed of creatures." },
      { key: "playerHealthPoints", label: "Player health points", type: "int", default: 15, min: 1, max: 999, step: 1,
        help: "Maximum health points at the start." },
      { key: "playerHealthRegenSpeed", label: "Health regen speed", type: "float", default: 1,
        min: 0.25, max: 2, step: 0.05, help: "Speed of health regeneration." },
      { key: "playerHungerSpeed", label: "Hunger speed", type: "float", default: 1, min: 0, max: 10, step: 0.1,
        help: "How fast hunger increases." },
      { key: "playerMoveSpeed", label: "Move speed", type: "float", default: 1.5, min: 0, max: 10, step: 0.1,
        help: "Player walking speed." },
      { key: "foodSpoilSpeed", label: "Food spoil speed", type: "float", default: 1, min: 0, max: 10, step: 0.1,
        help: "How fast food spoils." },
      { key: "saplingGrowthRate", label: "Sapling growth rate", type: "float", default: 1, min: 0, max: 20, step: 0.1,
        help: "Tree growth speed." },
      { key: "toolDurability", label: "Tool durability", type: "float", default: 1, min: 0, max: 99, step: 0.1,
        help: "Tool durability multiplier." },
      { key: "toolMiningSpeed", label: "Tool mining speed", type: "float", default: 1, min: 0, max: 99, step: 0.1,
        help: "Block mining speed." },
      { key: "propickNodeSearchRadius", label: "Prospecting radius", type: "int", default: 6, min: 0, max: 64, step: 1,
        help: "Search radius in the prospecting pick's node mode." },
      { key: "globalDepositSpawnRate", label: "Ore deposit spawn rate", type: "float", default: 1, min: 0, max: 20, step: 0.1,
        help: "Global frequency of ore deposits." },
      { key: "microblockChiseling", label: "Microblock chiseling", type: "enum", default: "stonewood",
        options: [
          { value: "off", label: "Off" },
          { value: "stonewood", label: "Stone & wood" },
          { value: "all", label: "All blocks" },
        ], help: "Which blocks may be chiseled." },
      { key: "loreContent", label: "Lore content", type: "bool", default: true,
        help: "Generate lore objects (scrolls etc.)." },
      { key: "clutterObtainable", label: "Clutter obtainable", type: "enum", default: "ifrepaired",
        options: [
          { value: "ifrepaired", label: "Only if repaired" },
          { value: "yes", label: "Yes" },
          { value: "no", label: "No" },
        ], help: "Whether decorative clutter objects can be picked up." },
      { key: "noLiquidSourceTransport", label: "No liquid source transport", type: "bool", default: false,
        help: "Prevents scooping of infinite liquid sources." },
      { key: "lightningFires", label: "Lightning fires", type: "bool", default: false,
        help: "Lightning strikes can ignite fires." },
    ],
  },

  {
    id: "worldgen",
    title: "World generation",
    note: "These settings only apply at world creation and cannot be changed afterwards.",
    fields: [
      { key: "worldClimate", label: "World climate", type: "enum", default: "realistic", creationOnly: true,
        options: [
          { value: "realistic", label: "Realistic" },
          { value: "patchy", label: "Patchy" },
        ], help: "Distribution of climate zones." },
      { key: "worldWidth", label: "World width (blocks)", type: "int", default: 1024000,
        min: 50000, max: 8192000, step: 1000, creationOnly: true, help: "Width of the world." },
      { key: "worldLength", label: "World length (blocks)", type: "int", default: 1024000,
        min: 50000, max: 8192000, step: 1000, creationOnly: true, help: "Length of the world." },
      { key: "polarEquatorDistance", label: "Polar-equator distance", type: "int", default: 50000,
        min: 5000, max: 800000, step: 1000, creationOnly: true,
        help: "Distance between pole and equator (climate gradient)." },
      { key: "landcover", label: "Landcover", type: "float", default: 0.975, min: 0, max: 1, step: 0.005,
        creationOnly: true, help: "Ratio of land to ocean." },
      { key: "oceanscale", label: "Ocean scale", type: "float", default: 5, min: 0.1, max: 5, step: 0.1,
        creationOnly: true, help: "Size of the oceans." },
      { key: "upheavelCommonness", label: "Upheaval commonness", type: "float", default: 0.3, min: 0, max: 1, step: 0.05,
        creationOnly: true, help: "Frequency of dramatic terrain upheaval." },
      { key: "geologicActivity", label: "Geologic activity", type: "float", default: 0.05, min: 0, max: 0.4, step: 0.01,
        creationOnly: true, help: "Frequency of volcanism / hot rock." },
      { key: "landformScale", label: "Landform scale", type: "float", default: 1.0, min: 0.2, max: 3, step: 0.1,
        creationOnly: true, help: "Size scaling of landforms." },
      { key: "worldEdge", label: "World edge", type: "enum", default: "traversable", creationOnly: true,
        options: [
          { value: "traversable", label: "Traversable" },
          { value: "blocked", label: "Blocked" },
        ], help: "Behaviour at the edge of the world." },
      { key: "storyStructuresDistScaling", label: "Story structure distance", type: "float", default: 1, min: 0.1, max: 10, step: 0.1,
        creationOnly: true, help: "Scales the distance of story structures." },
      { key: "globalTemperature", label: "Global temperature", type: "float", default: 1, min: 0, max: 5, step: 0.1,
        creationOnly: true, help: "Global temperature multiplier." },
      { key: "globalPrecipitation", label: "Global precipitation", type: "float", default: 1, min: 0, max: 5, step: 0.1,
        creationOnly: true, help: "Global precipitation multiplier." },
      { key: "globalForestation", label: "Global forestation", type: "float", default: 0, min: -1, max: 1, step: 0.05,
        creationOnly: true, help: "Shifts forest density (-1 less, 1 more)." },
      { key: "surfaceCopperDeposits", label: "Surface copper deposits", type: "float", default: 0.12, min: 0, max: 5, step: 0.01,
        creationOnly: true, help: "Frequency of surface copper deposits." },
      { key: "surfaceTinDeposits", label: "Surface tin deposits", type: "float", default: 0.007, min: 0, max: 5, step: 0.001,
        creationOnly: true, help: "Frequency of surface tin deposits." },
      { key: "snowAccum", label: "Snow accumulation", type: "bool", default: true, creationOnly: true,
        help: "Snow accumulates in layers." },
    ],
  },

  {
    id: "temporal",
    title: "Temporal stability",
    fields: [
      { key: "temporalStability", label: "Temporal stability", type: "bool", default: true,
        help: "Enable the stability mechanic." },
      { key: "temporalStorms", label: "Temporal storms", type: "enum", default: "sometimes",
        options: [
          { value: "off", label: "Off" },
          { value: "veryrare", label: "Very rare" },
          { value: "rare", label: "Rare" },
          { value: "sometimes", label: "Sometimes" },
          { value: "often", label: "Often" },
          { value: "veryoften", label: "Very often" },
        ], help: "Frequency of temporal storms." },
      { key: "tempstormDurationMul", label: "Storm duration multiplier", type: "float", default: 1, min: 0.1, max: 10, step: 0.1,
        help: "Lengthens/shortens storm duration." },
      { key: "temporalRifts", label: "Temporal rifts", type: "enum", default: "visible",
        options: [
          { value: "off", label: "Off" },
          { value: "invisible", label: "Invisible" },
          { value: "visible", label: "Visible" },
        ], help: "Rendering of temporal rifts." },
      { key: "temporalStormSleeping", label: "Sleeping during storm", type: "enum", default: "0",
        options: [
          { value: "0", label: "Not allowed" },
          { value: "1", label: "Allowed" },
        ], help: "Whether sleeping is allowed during a storm." },
    ],
  },

  {
    id: "worldmap",
    title: "World map",
    fields: [
      { key: "allowCoordinateHud", label: "Coordinate HUD", type: "bool", default: true,
        help: "Allow the coordinate display." },
      { key: "allowMap", label: "World map", type: "bool", default: true,
        help: "Allow the map feature." },
      { key: "colorAccurateWorldmap", label: "Color accurate map", type: "bool", default: false,
        help: "Map with true block colors." },
    ],
  },

  {
    id: "multiplayer",
    title: "Multiplayer",
    fields: [
      { key: "allowLandClaiming", label: "Land claiming", type: "bool", default: true,
        help: "Players can claim land." },
      { key: "classExclusiveRecipes", label: "Class exclusive recipes", type: "bool", default: true,
        help: "Certain recipes only for matching classes." },
      { key: "auctionHouse", label: "Auction house", type: "bool", default: true,
        help: "Enable the auction house system." },
    ],
  },
];

const FIELDS_BY_KEY = {};
for (const cat of SCHEMA) {
  for (const f of cat.fields) FIELDS_BY_KEY[f.key] = f;
}

// Top-level serverconfig.json settings with native JSON types (not inside
// WorldConfiguration). Defaults mirror a server-generated serverconfig.json.
const SERVER_SCHEMA = [
  {
    id: "srv-network",
    title: "Server identity & network",
    fields: [
      { key: "ServerName", label: "Server name", type: "string", default: "Vintage Story Server",
        help: "Name shown in the server browser." },
      { key: "ServerUrl", label: "Server URL", type: "string", nullable: true, default: null,
        help: "Optional website URL." },
      { key: "ServerDescription", label: "Server description", type: "string", nullable: true, default: null,
        help: "Optional description (empty = none)." },
      { key: "WelcomeMessage", label: "Welcome message", type: "string",
        default: "Welcome {0}, may you survive well and prosper", help: "{0} is replaced by the player name." },
      { key: "Ip", label: "Bind IP", type: "string", nullable: true, default: null,
        help: "IP to bind to (empty = all interfaces)." },
      { key: "Port", label: "Port", type: "int", default: 42420, help: "TCP port the server listens on." },
      { key: "Upnp", label: "UPnP port forwarding", type: "bool", default: false },
      { key: "UpnpInfiniteLifetime", label: "UPnP infinite lifetime", type: "bool", default: false },
      { key: "CompressPackets", label: "Compress packets", type: "bool", default: true },
      { key: "AdvertiseServer", label: "Advertise to public list", type: "bool", default: false,
        help: "List the server on the public master server." },
      { key: "MasterserverUrl", label: "Master server URL", type: "string",
        default: "http://masterserver.vintagestory.at/api/v1/servers/", help: "Rarely changed." },
      { key: "ModDbUrl", label: "Mod DB URL", type: "string", default: "https://mods.vintagestory.at/",
        help: "Rarely changed." },
      { key: "ClientConnectionTimeout", label: "Client connection timeout (s)", type: "int", default: 150 },
      { key: "Password", label: "Password", type: "string", nullable: true, default: null,
        help: "Server password (empty = none)." },
      { key: "ServerLanguage", label: "Server language", type: "enum", default: "en",
        options: [
          { value: "en", label: "English" }, { value: "de", label: "German" },
          { value: "fr", label: "French" }, { value: "es-es", label: "Spanish" },
          { value: "ru", label: "Russian" }, { value: "zh-cn", label: "Chinese" },
          { value: "pt-br", label: "Portuguese (BR)" }, { value: "it", label: "Italian" },
          { value: "nl", label: "Dutch" }, { value: "pl", label: "Polish" },
          { value: "uk", label: "Ukrainian" }, { value: "ja", label: "Japanese" },
          { value: "ko", label: "Korean" }, { value: "cs", label: "Czech" },
          { value: "sv-se", label: "Swedish" }, { value: "tr", label: "Turkish" },
        ], help: "Language used for server-side messages." },
    ],
  },

  {
    id: "srv-players",
    title: "Server players & slots",
    fields: [
      { key: "MaxClients", label: "Max clients", type: "int", default: 16 },
      { key: "MaxClientsInQueue", label: "Max clients in queue", type: "int", default: 0 },
      { key: "WarnClientsAfterAfkSeconds", label: "Warn after AFK (s)", type: "int", default: 0,
        help: "0 = disabled." },
      { key: "KickClientsAfterAfkSeconds", label: "Kick after AFK (s)", type: "int", default: 0,
        help: "0 = disabled." },
      { key: "PassTimeWhenEmpty", label: "Pass time when empty", type: "bool", default: false,
        help: "Advance world time when no players are online." },
    ],
  },

  {
    id: "srv-world",
    title: "Server world & gameplay",
    fields: [
      { key: "MapSizeX", label: "Map size X (blocks)", type: "int", default: 1024000 },
      { key: "MapSizeY", label: "Map height Y (blocks)", type: "int", default: 256,
        help: "Vertical world size." },
      { key: "MapSizeZ", label: "Map size Z (blocks)", type: "int", default: 1024000 },
      { key: "MaxChunkRadius", label: "Max chunk radius", type: "int", default: 12,
        help: "Maximum view distance in chunks." },
      { key: "DefaultSpawn", label: "Default spawn", type: "string", nullable: true, default: null,
        help: "Usually empty (null) — leave blank for the generated spawn." },
      { key: "AllowPvP", label: "Allow PvP", type: "bool", default: true },
      { key: "AllowFireSpread", label: "Allow fire spread (server)", type: "bool", default: true,
        help: "Top-level server toggle (separate from the world config one)." },
      { key: "AllowFallingBlocks", label: "Allow falling blocks (server)", type: "bool", default: true,
        help: "Top-level server toggle (separate from the world config one)." },
      { key: "StartupCommands", label: "Startup commands", type: "string", nullable: true, default: null,
        help: "Commands run on startup (empty = none)." },
    ],
  },

  {
    id: "srv-security",
    title: "Server security & groups",
    fields: [
      { key: "AntiAbuse", label: "Anti-abuse level", type: "int", default: 0 },
      { key: "GroupChatHistorySize", label: "Group chat history size", type: "int", default: 20 },
      { key: "MaxOwnedGroupChannelsPerUser", label: "Max owned group channels / user", type: "int", default: 10 },
      { key: "OnlyWhitelisted", label: "Only whitelisted", type: "bool", default: false },
      { key: "WhitelistMode", label: "Whitelist mode", type: "int", default: 1,
        help: "Server whitelist mode (0 off / 1 default)." },
      { key: "VerifyPlayerAuth", label: "Verify player auth", type: "bool", default: true },
      { key: "ChatRateLimitMs", label: "Chat rate limit (ms)", type: "int", default: 1000 },
      { key: "LoginFloodProtection", label: "Login flood protection", type: "bool", default: false },
      { key: "TemporaryIpBlockList", label: "Temporary IP block list", type: "bool", default: false },
    ],
  },

  {
    id: "srv-ops",
    title: "Server performance & operations",
    fields: [
      { key: "EntityDebugMode", label: "Entity debug mode", type: "bool", default: false },
      { key: "TickTime", label: "Tick time (ms)", type: "float", default: 33.333332, step: 0.001 },
      { key: "SpawnCapPlayerScaling", label: "Spawn cap player scaling", type: "float", default: 0.5, step: 0.05 },
      { key: "BlockTickChunkRange", label: "Block tick chunk range", type: "int", default: 5 },
      { key: "MaxMainThreadBlockTicks", label: "Max main-thread block ticks", type: "int", default: 10000 },
      { key: "RandomBlockTicksPerChunk", label: "Random block ticks / chunk", type: "int", default: 16 },
      { key: "BlockTickInterval", label: "Block tick interval (ms)", type: "int", default: 300 },
      { key: "SkipEveryChunkRow", label: "Skip every chunk row", type: "int", default: 0 },
      { key: "SkipEveryChunkRowWidth", label: "Skip chunk row width", type: "int", default: 0 },
      { key: "RepairMode", label: "Repair mode", type: "bool", default: false },
      { key: "AnalyzeMode", label: "Analyze mode", type: "bool", default: false },
      { key: "CorruptionProtection", label: "Corruption protection", type: "bool", default: true },
      { key: "RegenerateCorruptChunks", label: "Regenerate corrupt chunks", type: "bool", default: false },
      { key: "DieBelowDiskSpaceMb", label: "Die below disk space (MB)", type: "int", default: 400 },
      { key: "LogBlockBreakPlace", label: "Log block break/place", type: "bool", default: false },
      { key: "LogFileSplitAfterLine", label: "Log file split after lines", type: "int", default: 500000 },
      { key: "DieAboveErrorCount", label: "Die above error count", type: "int", default: 100000 },
      { key: "DieAboveMemoryUsageMb", label: "Die above memory usage (MB)", type: "int", default: 50000 },
    ],
  },
];

// World config overrides per preset playstyle, relative to Standard (= schema
// defaults). Best-effort values from https://wiki.vintagestory.at/Preset_playstyles
// (may differ by game version). Applying a preset resets all other world fields.
const PLAYSTYLE_PRESETS = {
  surviveandbuild: {}, // Standard

  exploration: {
    graceTimer: 5,
    deathPunishment: "keep",
    playerHealthPoints: 20,
    playerHungerSpeed: 0.5,
    creatureHostility: "passive",
    temporalStability: false,
    temporalStorms: "off",
    temporalGearRespawnUses: -1,
    toolDurability: 2,
    propickNodeSearchRadius: 8,
    surfaceCopperDeposits: 0.2,
    microblockChiseling: "all",
  },

  wildernesssurvival: {
    spawnRadius: 5000,
    playerHealthPoints: 10,
    playerHungerSpeed: 1.25,
    creatureStrength: 1.5,
    caveIns: "on",
    temporalStorms: "often",
    temporalGearRespawnUses: 3,
    allowCoordinateHud: false,
    allowMap: false,
    microblockChiseling: "off",
    propickNodeSearchRadius: 0,
  },

  homosapiens: {
    spawnRadius: 5000,
    playerHealthPoints: 10,
    creatureStrength: 1.5,
    loreContent: false,
    temporalStability: false,
    temporalStorms: "off",
    temporalRifts: "off",
    temporalGearRespawnUses: 0,
    allowCoordinateHud: false,
    allowMap: false,
    microblockChiseling: "off",
    propickNodeSearchRadius: 0,
    polarEquatorDistance: 200000,
  },

  creativebuilding: {
    gameMode: "creative",
    deathPunishment: "keep",
    playerHealthPoints: 20,
    playerHungerSpeed: 0,
    creatureHostility: "off",
    creatureStrength: 0,
    temporalStability: false,
    temporalStorms: "off",
    temporalRifts: "off",
    temporalGearRespawnUses: -1,
    loreContent: false,
    microblockChiseling: "all",
    propickNodeSearchRadius: 8,
  },
};
